### ISSUE TITLE
Change artisan command and prefix

### ISSUE THREAD

**Issue by Lednerb** [wdelfuego/nova-calendar#15]
Hi @wdelfuego and thanks for this great package.

I'd like to request the following change:

To create the default calendar data provider there is the following artisan command provided by this package:
```bash
php artisan create:default-calendar-data-provider
```

The command should be refactored to the following usage:

```bash
php artisan nova-calendar:create-default-calendar-data-provider
```

This will ensure that you can add more commands in the future under the same namespace and will separate the CLI from default artisan commands to those that are supported by third parties.

If you agree with this change I will submit the needed changes as a PR in the next days.

**Comment by wdelfuego** [comment]
HI @Lednerb, good point, thanks for your input!

I agree to the change and will accept the PR. 

Maybe `nova-calendar:create-default-data-provider` would be even better since the `nova-calendar` prefix already indicates what it's for and I don't expect the calendar to have any non-calendar data providers anytime soon ;)

I know you're aware of this because of your thumbs up on my comment in the PHP7 support PR but for completeness' sake, please check that you agree to your changes being distributed under this package's [dual licensing model](https://github.com/wdelfuego/nova-calendar/blob/main/LICENSE.md).

Related; I'm playing with the idea of changing the naming from dataprovider to datasource since providers in Laravel apps are generally service providers and not data providers, if you have any thoughts on that naming / architectural issue I'd be happy to hear them, too.

Thanks for helping!

**Comment by Lednerb** [comment]
> I know you're aware of this because of your thumbs up on my comment in the PHP7 support PR but for completeness' sake, please check that you agree to your changes being distributed under this package's [dual licensing model](https://github.com/wdelfuego/nova-calendar/blob/main/LICENSE.md).

I'm absolutely fine with it. Btw I like your dual licensing model a lot and consider to use it maybe in the future for my projects as well. (Also btw.: Maybe it's nice to link the GNU License in the `README.md` with https://choosealicense.com/licenses/agpl-3.0/ for an easy overview)

---

> Related; I'm playing with the idea of changing the naming from dataprovider to datasource since providers in Laravel apps are generally service providers and not data providers, if you have any thoughts on that naming / architectural issue I'd be happy to hear them, too.

Actually I like the `DataProvider` naming convention because it feels like the laravel way of naming it, altough most of the times `ServiceProvider`s are used. But I don't think that it is misleading or a naming issue in this case.

I associate a `DataSource` to different things like external databases, queues, local directories or external APIs and that's not the case here. 

Within the `CalendarDataProvider.php` I have to _provide_ the _data_ for the _calendar_ tool.

It's a good name, let's stick with it! ;-)
