### ISSUE TITLE
How can I have two or more distinct calendars ?

### ISSUE THREAD

**Issue by vesper8** [wdelfuego/nova-calendar#43]
I would like to have multiple calendars, completely distinct from each other, on different URIs.

I see how I can change the URI of a single calendar, but can't seem to figure out how to have two distinct calendars.

Some guidance would be much appreciated.

Many thanks!

**Comment by wdelfuego** [comment]
This is currently not possible, since the CalendarDataProvider is provided to the CalendarController through dependency injection. I agree that it would be a valuable feature to have so I'd be happy to help you implement this. I won't work on this myself on short notice since there are other features that are higher on my own list of priorities (event filtering & week view).

There is already an [issue for this feature request](https://github.com/wdelfuego/nova-calendar/issues/3) so I'll close this one.

Let me know if you're interested in developing this feature and we'll get in touch to make sure you're successful :).

**Comment by wdelfuego** [comment]
Nice, glad you got this to work and thanks for sharing your solution!

If the package is going to support multiple calendar instances, I will require a different calendar data provider per calendar view since the calendar data provider is already at risk of growing to a god object, let alone when you need to detect the requested view in every of its methods. I have hidden your comment from issue #3 since it is not relevant to that specific issue (supplying a different calendar data provider to the CalendarController) and am reproducing it here because it is relevant to people who are interested in using your solution in the meantime:

> Well with very little effort I was able to hack something together that allows for this. Here's how I did it.
> 
> First I needed to add multiple new routes that would all lead to the same calendar. So inside my `NovaServiceProvider.php` boot method I added
> 
> ```
> 
>         $this->app->booted(function () {
>             Nova::router(['nova', \Wdelfuego\NovaCalendar\Http\Middleware\Authorize::class], 'bookings-calendar')
>             ->group(base_path('vendor/wdelfuego/nova-calendar/routes/inertia.php'));
> 
>             Nova::router(['nova', \Wdelfuego\NovaCalendar\Http\Middleware\Authorize::class], 'lessons-calendar')
>             ->group(base_path('vendor/wdelfuego/nova-calendar/routes/inertia.php'));
>         });
> ```
> 
> So now I have two routes that lead to my calendar `/nova/bookings-calendar` and `/nova/lessons-calendar`
> 
> Then, inside my CalendarDataProvider I simply need to know which route I'm on and based on this I'll use different resources.
> 
> Here's how I did that:
> 
> ```
> 
> 
>     public function novaResources(): array
>     {
>         switch(basename(request()->server('HTTP_REFERER'))) {
>             case 'bookings-calendar':
>                 $resources = [
>                     \App\Nova\Resources\Bookings\Booking::class => ['starts_at', 'ends_at'],
>                 ];
>                 break;
> 
>             case 'lessons-calendar':
>                 $resources = [
>                     \App\Nova\Resources\Bookings\BookingLesson::class => 'created_at',
>                 ];
>                 break;
>         }
> 
>         return $resources;
>     }
> ```
> 
> And voila! Easy-peasy ;-)

**Comment by vesper8** [comment]
I thought about the "god object" case and quickly came up with something that would work to prevent that.

Basically inside the config file you could have an associative array of route paths and resourceProvider classes. And then inside the data provider you could use that mapping to essentially abstract the data provider.

So something like this in the config file:

```

            'calendars' => [
                'bookings-calendar' => BookingCalendarDataProvider::class,
                'lessons-calendar' => LessonCalendarDataProvider::class,
            ],
```

And then inside the novaResources function

```

$resources = (new config('nova-calendar.calendars')[basename(request()->server('HTTP_REFERER'))])->getResources();
```


Proof of concept but it would allow for some abstraction and would work with the way you're currently doing things.

You could loop over these calendars from the config as well when setting up the extra routes.

**Comment by wdelfuego** [comment]
Thanks a lot for your input! I'll be exploring something analogous to this, hope to launch the feature with version 2.0 in January or February.
