### ISSUE TITLE
Poor performance - eager loading breaks in Custom Event Generators

### ISSUE THREAD

**Issue by SamMakesCode** [wdelfuego/nova-calendar#52]
### Problem

We've created a custom event generator to handle bookings for our customers.

```
class BookingEventGenerator extends CustomEventGenerator
{
    protected function modelQuery(EloquentBuilder $queryBuilder, Carbon $startOfCalendar, Carbon $endOfCalendar): EloquentBuilder
    {
        return $queryBuilder
            ->with([
                'electrician',
            ])
            ->where('from', '>=', $startOfCalendar)
            ->where('from', '<=', $endOfCalendar)
            ;
    }

    protected function resourceToEvents(NovaResource $resource): array
    {
        $out = [];
        
        $model = $resource->model();

        $event = new Event(
            'Booking #' . $model->id,
            $model->from,
            $model->to,
        );

        $event->notes('<b>Installer: </b>' . $model->electrician->first_name . ' ' . $model->electrician->last_name);

        $out[] = $event;

        return $out;
    }
}
```

We've eager loaded the electrician relationship in the query because we don't want to reload it every time we handle an event. BUT, the `nova-calendar` library uses `->cursor()` on the relationship in `->generateEvents()`. This will only keep one relationship in memory at a time meaning a separate query is run to get the relationship for every event.

### How we solved it

We've got a fork of your project and for our purposes, swapping `->cursor()` to `->get()` works fine.

It'd be nice though, if `nova-calendar` could allow you to specify the method used in a custom event generator, or something similar.

**Comment by wdelfuego** [comment]
Hi Sam,

In principle, you don't need to implement a custom event generator if you are generating precisely one calendar event for each Nova resource to be displayed on the calendar.

But since you are, I don't think you need to maintain a fork for this; you're already subclassing `CustomEventGenerator` so you could simply override the implementation of the `generateEvents` method to use `get` instead of `cursor` while iterating over your models.

I am assuming that the current `cursor` behavior is the best default for consumers of this package and since subclassing already allows you to override this behavior without needing a fork, I'm not convinced that this has to be a configurable option.

Having this issue documented here is a good thing though so thanks again for reporting :)!
